%% xcorrtest.m
% This script plots the USRP cross correlation data as well as a MATLAB
% correlation for comparison

% Found in the slavenode build folder, not entirely sure why this was here.

%% Pulse configuration
fs = 100e3;     % Sampling Frequency
ts = 1/fs;      % Sampling Period
cbw = 1;        % Carrier bandwidth
bw = 0.75;      % Sinc pulse bandwidth
tau = 0;        % Delay for sinc pulse generated in MATLAB
ampl = 2048;    % Amplitude of since pulse generated in MATLAB
threshold = 2e7;

folder = './';

%% Open received .dat file from USRP 1

filenam = [folder 'rx.dat'];
fid=fopen(filenam,'r');
rx=fread(fid,Inf,'int16');
fclose(fid);
rx=rx(1:2:end)+1j*rx(2:2:end);

% trim the RX buffer
rxbegin = 1;             % Must be greater than 0
rxend   = length(rx);       % Must be less than length(rxt)

rxfull = rx;
rx = rx(rxbegin:rxend);
rxt = rxbegin:rxend;
% Plot the pulse, imaginary is blue real is red
figure(1);
% plot(rxt,imag(rx),'b',rxt,real(rx),'r');
plot(rxt,imag(rx),'b');
title('USRP Received Waveform');

%% Open sinc.dat file from USRP 2
filenam = [folder 'xcorr_sinc.dat'];
fid=fopen(filenam,'r');
sinc1=fread(fid,Inf,'int16');
fclose(fid);
sinc1=sinc1(1:2:end)+1j*sinc1(2:2:end);
% Plot the pulse, imaginary is blue real is red
figure(2);
sinct = 1:length(sinc1);
plot(sinct,imag(sinc1),'b-*',sinct,real(sinc1),'r-*');
title('SINC function generated by USRP');

%% Compute the cross correlation and plot the normalized result
%ccorr = xcorr(sinc1,rx);
ccorr = conv(flipud((sinc1)),rx);
figure(3)
plot(abs(ccorr.^2));
axis([0 length(ccorr) 0 abs(max(ccorr)).^2])
title('MATLAB Cross Correlation');

%% Plot USRP's xcorr
% fid=fopen('xcorr2.dat','r');
filenam = [folder 'xcorr.dat'];
fid=fopen(filenam,'r');
usrpCorr=fread(fid,Inf,'int64');
fclose(fid);
usrpCorr=usrpCorr(1:2:end)+1j*usrpCorr(2:2:end);
figure(4)
usrpCorr = usrpCorr(rxbegin:rxend);
plot((real(usrpCorr)));
axis([0 length(usrpCorr) 0 max(usrpCorr)])
title('USRP Cross Correlation');
line([1 length(usrpCorr)],[threshold threshold],'Color',[1 0 0])

%% Compute cross correlation (replicated from USRP code)
% SynUSRPxcorr = USRPcorr(sinc1,rxfull,1000);
% figure(5)
% SynUSRPxcorr = SynUSRPxcorr';
% SynUSRPxcorr = SynUSRPxcorr(rxbegin:end);
% plot(SynUSRPxcorr);
% axis([0 length(SynUSRPxcorr) 0 max(SynUSRPxcorr)])
% title('MATLAB synthesized cross correlation (using USRP alg.)');

%% Plot abs^2 of rx to verify correlation amplitudes
figure(6)
plot(abs(rx).^2);
axis([0 length(rx) 0 max(abs(rx).^2)])
title('abs(rx).^2');
